export const theme = {
    base00: "rgba(255,255,255,0)",
    base01: "black",
    base02: "black",
    base03: "black",
    base04: "black",
    base05: "black",
    base06: "black",
    base07: "black",
    base08: "black",
    base09: "black",
    base0A: "black",
    base0B: "black",
    base0C: "black",
    base0D: "black",
    base0E: "black",
    base0F: "black",
}